site_name: epsilon0112358
theme:
    name: material
    palette:
        scheme: slate
        primary: light green
        accent: teal
    features:
        - navaigation.indexes
        - navigation.footer
    logo: assets/images/epsilon.jpeg
    favicon: assets/images/epsilon.jpeg
nav:
    - Home: index.md
    - Blog:
        - blog/index.md
    - Knowledge base:
        - knowledge/blog_setup.md
        - knowledge/MVPs.md
    - About: about.md   
plugins:
    - blog
    - git-revision-date-localized:
        type: date